"""create links table

Revision ID: 9342f8782981
Revises: 94ef9147cea9
Create Date: 2026-01-10 12:54:45.864017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9342f8782981'
down_revision: Union[str, Sequence[str], None] = '94ef9147cea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('links',
                    sa.Column('link', sa.String(), nullable=False),
                    sa.Column('status', sa.Boolean(), nullable=False),
                    sa.Column('views', sa.Integer(), nullable=False),
                    sa.PrimaryKeyConstraint('link')
                    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('links')
    # ### end Alembic commands ###
