// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.12
// source: protos/checker.proto

package checkerv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CheckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           []string               `protobuf:"bytes,1,rep,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckRequest) Reset() {
	*x = CheckRequest{}
	mi := &file_protos_checker_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckRequest) ProtoMessage() {}

func (x *CheckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_checker_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckRequest.ProtoReflect.Descriptor instead.
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return file_protos_checker_proto_rawDescGZIP(), []int{0}
}

func (x *CheckRequest) GetUrl() []string {
	if x != nil {
		return x.Url
	}
	return nil
}

type CheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Urls          []*Url                 `protobuf:"bytes,1,rep,name=urls,proto3" json:"urls,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckResponse) Reset() {
	*x = CheckResponse{}
	mi := &file_protos_checker_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckResponse) ProtoMessage() {}

func (x *CheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_checker_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckResponse.ProtoReflect.Descriptor instead.
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return file_protos_checker_proto_rawDescGZIP(), []int{1}
}

func (x *CheckResponse) GetUrls() []*Url {
	if x != nil {
		return x.Urls
	}
	return nil
}

type Url struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status        bool                   `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Url) Reset() {
	*x = Url{}
	mi := &file_protos_checker_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Url) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Url) ProtoMessage() {}

func (x *Url) ProtoReflect() protoreflect.Message {
	mi := &file_protos_checker_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Url.ProtoReflect.Descriptor instead.
func (*Url) Descriptor() ([]byte, []int) {
	return file_protos_checker_proto_rawDescGZIP(), []int{2}
}

func (x *Url) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Url) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

var File_protos_checker_proto protoreflect.FileDescriptor

const file_protos_checker_proto_rawDesc = "" +
	"\n" +
	"\x14protos/checker.proto\x12\achecker\" \n" +
	"\fCheckRequest\x12\x10\n" +
	"\x03url\x18\x01 \x03(\tR\x03url\"1\n" +
	"\rCheckResponse\x12 \n" +
	"\x04urls\x18\x01 \x03(\v2\f.checker.UrlR\x04urls\"/\n" +
	"\x03Url\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06status\x18\x02 \x01(\bR\x06status2F\n" +
	"\aChecker\x12;\n" +
	"\n" +
	"CheckLinks\x12\x15.checker.CheckRequest\x1a\x16.checker.CheckResponseB\x19Z\x17protos/gen-go/checkerv1b\x06proto3"

var (
	file_protos_checker_proto_rawDescOnce sync.Once
	file_protos_checker_proto_rawDescData []byte
)

func file_protos_checker_proto_rawDescGZIP() []byte {
	file_protos_checker_proto_rawDescOnce.Do(func() {
		file_protos_checker_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_checker_proto_rawDesc), len(file_protos_checker_proto_rawDesc)))
	})
	return file_protos_checker_proto_rawDescData
}

var file_protos_checker_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_checker_proto_goTypes = []any{
	(*CheckRequest)(nil),  // 0: checker.CheckRequest
	(*CheckResponse)(nil), // 1: checker.CheckResponse
	(*Url)(nil),           // 2: checker.Url
}
var file_protos_checker_proto_depIdxs = []int32{
	2, // 0: checker.CheckResponse.urls:type_name -> checker.Url
	0, // 1: checker.Checker.CheckLinks:input_type -> checker.CheckRequest
	1, // 2: checker.Checker.CheckLinks:output_type -> checker.CheckResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protos_checker_proto_init() }
func file_protos_checker_proto_init() {
	if File_protos_checker_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_checker_proto_rawDesc), len(file_protos_checker_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_checker_proto_goTypes,
		DependencyIndexes: file_protos_checker_proto_depIdxs,
		MessageInfos:      file_protos_checker_proto_msgTypes,
	}.Build()
	File_protos_checker_proto = out.File
	file_protos_checker_proto_goTypes = nil
	file_protos_checker_proto_depIdxs = nil
}
